CREATE TABLE USER (USERID BIGINT NOT NULL, EMAIL VARCHAR, NAME VARCHAR, PASSWORD VARCHAR, ROL VARCHAR, SURNAME VARCHAR, PRIMARY KEY (USERID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
